import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Turborepo",
  description: "Generated by create turbo",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}): JSX.Element {
  return (
    <html lang="en">
      <body className={inter.className}>
        {children}
        <br />
        <div className="bg-black text-lg font-semibold p-2 text-white">
          ||||||||||||| Layout-Merchant_app |||||||||||||||
        </div>
      </body>
    </html>
  );
}
